<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>RayTracer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="StbImageSharp" Version="2.30.15" />
        <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
    </ItemGroup>

</Project>
